title: Godbey Status
buildFuture: true
defaultContentLanguage: en
languageCode: en
params:
  disableDarkMode: false
  shortDateFormat: 15:04 — Jan 2
  down: "#e60000"
  systems:
    - name: Router
      category: Network
      description: The router/connection to suddenlink's network.
    - name: Godbey Wifi & Godbey Wifi5G
      category: Network
      description: The main wifi access point located in Pop's closet.
    - name: Garage Cam
      category: Cameras
      description: Camera looking down the driveway
    - name: Side Yard Cam
      category: Cameras
      description: Camera pointed at sidewalk side of house.
    - name: Front Porch Cam
      category: Cameras
      description: Front porch camera
    - name: Downstairs Camera
      category: Cameras
      description: Camera on downstairs porch
    - name: Godbey North
      category: Network
      description: The Godbey Wifi North access point located beneath Jack's window.
    - name: Cable Modem
      category: Network
      description: Internet interface w/ Suddenlink
  dateFormat: January 2, 2006 at 3:04 PM
  brand: "#0a0c0f"
  headerTextColor: white
  logo: /logo.png
  incidentPostsPerPage: 10
  googleAnalytics: UA-00000000-1
  alwaysKeepBrandColor: true
  disableComplexCalculations: false
  useLogo: false
  disrupted: "#cc4400"
  notice: "#24478f"
  incidentHistoryFormat: yearly
  disableIncidentHistory: true
  ok: "#008000"
  categories:
    - name: Network
      description: Local area network and wifi at the house
      closed: false
    - name: Cameras
      untitled: true
      closed: false
  description: Status page for Godbey properties, networks, and internet connection.
  enableCustomHTML: true
  useLargeHeaderDesign: false
theme: cstate
preserveTaxonomyNames: true
taxonomies:
  affected: affected
outputs:
  page:
    - html
    - json
  section:
    - html
    - json
    - rss
  home:
    - html
    - json
    - rss
    - svg
outputFormats:
  svg:
    isPlainText: true
    mediaType: image/svg+xml
baseURL: https://status.godbey.host
