title: Godbey Status
buildFuture: true
defaultContentLanguage: en
languageCode: en
params:
  disableDarkMode: false
  shortDateFormat: 15:04 — Jan 2
  down: "#e60000"
  systems:
    - name: Gateway
      category: North Coast
    - name: Backup Gateway
      category: East Coast
    - name: API
      description: The guts of the application.
      category: Uncategorized
    - name: Media Proxy
      description: This is the service responsible for serving images, audio, and
        video. It is reliant on our CDN.
      category: Uncategorized
  dateFormat: January 2, 2006 at 3:04 PM
  brand: "#0a0c0f"
  headerTextColor: white
  logo: /logo.png
  incidentPostsPerPage: 10
  googleAnalytics: UA-00000000-1
  alwaysKeepBrandColor: true
  disableComplexCalculations: false
  useLogo: false
  disrupted: "#cc4400"
  notice: "#24478f"
  incidentHistoryFormat: yearly
  disableIncidentHistory: true
  ok: "#008000"
  categories:
    - name: Lan/WiFi
      description: Local area network and wifi at the house
      closed: true
    - name: "Suddenlink "
      description: External internet connection
    - name: Security cameras
      untitled: true
  description: Status page for Godbey properties, networks, and internet connection.
  enableCustomHTML: true
  useLargeHeaderDesign: false
theme: cstate
preserveTaxonomyNames: true
taxonomies:
  affected: affected
outputs:
  page:
    - html
    - json
  section:
    - html
    - json
    - rss
  home:
    - html
    - json
    - rss
    - svg
outputFormats:
  svg:
    isPlainText: true
    mediaType: image/svg+xml
baseURL: https://cstate.mnts.lt
